POST https://63069afec0d0f2b8011f9944.mockapi.io/produtos
Content-Type: application/json



//{"loja": "Candylandia", "nome": "TRIBALA 100G UVA", "imagem": "https://static.lojadedoces.com.br//produto/1_334259_1_7906.png", "imagem2": "https://cdn.awsli.com.br/300x300/1279/1279312/produto/70869372/d8cb3c6ff4.jpg", "estrelas": "4.2", "preco": "2,70", "descricao": "Experimente a Tribala Uva! Uma bala macia, com casquinha crocante e super recheada como nenhuma outra!"}
//{"loja": "Candylandia", "nome": "Stikadinho Morango 32un", "imagem": "https://static.lojadedoces.com.br//produto/1_517645_1_7307.png", "imagem2": "https://www.bigfesta.com.br/resizer/view/600/600/true/false/27073.jpg", "estrelas": "4.3", "preco": "18,99", "descricao": "O chocolate Stikadinho Morango têm um sabor único e inconfundível, perfeito para você. Ideal para fazer parte de sua festa, dia das crianças e festas de aniversário ou entregá-lo como lembrancinhas de seu evento. Se divirta, saboreie e brinque muito com seus amigos."}
//{"loja": "Candylandia", "nome": "Remix Castanha 25g Mãe Terra", "imagem": "https://static.lojadedoces.com.br//produto/1_435215_1_7360.png", "imagem2": "https://www.maeterra.com.br/sk-eu/content/dam/brands/mae_terra/brazil/53254510-7896496972500-01.png.rendition.767.767.png", "estrelas": "3.9", "preco": "4,45", "descricao": "Mix saudável de bolso pra você levar para qualquer lugar. Com 3 castanhas do nosso Brasil: da Amazônia, a castanha-do-pará; do Cerrado, o baru; da Caatinga, a castanha-de-caju, em uma combinação saborosa com o docinho natural das uvas passas. E, o melhor, não tem adição nem de sal, é purinho, purinho! O Remix Castanhas reúne tudo de melhor num lanchinho só: valoriza os ingredientes da biodiversidade brasileira, é puro e 100% natural, nutritivo e muito prático. Tem como ser mais perfeito? As castanhas são naturalmente ricas em gorduras boas, fibras, minerais, vitaminas e antioxidantes."}
//{"loja": "Candylandia", "nome": "MENTOS STICK 16UN FANTA LARANJA 24 PERFETTI", "imagem": "https://static.lojadedoces.com.br//produto/multifotos/hd/1_764643_1.png", "imagem2": "https://us-southeast-1.linodeobjects.com/storage/figurasupermercado/media/uploads/produto/mentos_stick_fanta_37_5gr_4879e2c8-30bb-4214-8bcb-d25206cda237.jpg", "estrelas": "4.1", "preco": "39,99", "descricao": "A Mentos e o refrigerante Fanta fizeram uma colaboração inédita: as duas marcas se uniram para criar o novo Mentos Fanta. As balas possuem o característico sabor da Fanta Laranja, misturado com a refrescância marcante do Mentos."}

//{"loja": "Candylandia", "nome": "TUBES SMOOFREE FRUTAS VERMELHAS PCT 80G 12 FINI", "imagem": "https://static.lojadedoces.com.br//produto/1_759342_1.png", "imagem2": "", "estrelas": "4.7", "preco": "6,59", "descricao": "Smoofree veganamente incrível! É delicioso com suco de fruta. É surpreendente como um smoothie e ainda é Fini! Tem receita melhor que essa? Você vai se encantar pelo sabor delicioso de frutas vermelhas, disponível em 80g, ideal para compartilhar com amigos e levar onde quiser."}
//{"loja": "Candylandia", "nome": "MENTOS CLEAR BREATH DP 9UN ORANGEMINT", "imagem": "https://static.lojadedoces.com.br//produto/multifotos/hd/20230123123402_8553991447_DZ.png", "imagem2": "", "estrelas": "4.7", "preco": "54,99", "descricao": "Sem açúcar Ingredientes Edulcorantes sorbitol, aspartame, acesulfame de potássio, sucralose e neotame,aromatizantes, antiumectante estearato de magnésio e corante azul brilhante FCF. Especificidades alimentares Contém glúten. Componentes alérgicos - Contém derivados de trigo. - Contém fenilalanina. Informações nutricionais Porção de 20g (29 unidades) Quantidade por porção - Valor energético: 48kcal=200kJ - Carboidratos: 19g Não contém quantidade significativa de proteínas, gorduras totais, gorduras saturadas, gorduras trans, fibra alimentar e sódio"}
//{"loja": "Candylandia", "nome": "PIRULITO BLONG 24UN ENERGY MIX", "imagem": "https://static.lojadedoces.com.br//produto/1_736138_1_7902.png", "imagem2": "", "estrelas": "4.6", "preco": "13,89", "descricao": "O sabor inconfundível do Blong Energy com um toque especial! Foi assim que nasceu o Pirulito Blong Energy Mix."}
//{"loja": "Candylandia", "nome": "BALA FANTASY FESTA VERMELHA 420G", "imagem": "https://static.lojadedoces.com.br//produto/1_668866_1_7984.png", "imagem2": "", "estrelas": "4.8", "preco": "8,69", "descricao": "Uma bala saborosa, crocante por fora e macia por dentro, a Fantasy Festa é perfeita para colorir qualquer momento da sua vida. Pode ser usada em festas de aniversário, decorações e como lembrancinha."}

//{"loja": "Candylandia", "nome": "", "imagem": "", "imagem2": "", "estrelas": "", "preco": "", "descricao": ""}
//{"loja": "Candylandia", "nome": "", "imagem": "", "imagem2": "", "estrelas": "", "preco": "", "descricao": ""}
//{"loja": "Candylandia", "nome": "", "imagem": "", "imagem2": "", "estrelas": "", "preco": "", "descricao": ""}
//{"loja": "Candylandia", "nome": "", "imagem": "", "imagem2": "", "estrelas": "", "preco": "", "descricao": ""}